package model;
// Generated Dec 22, 2019 8:33:35 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Aseguradoras generated by hbm2java
 */
public class Aseguradoras  implements java.io.Serializable {


     private int idaseguradora;
     private String aseguradora;
     private Date auFechainsert;
     private Integer auUserinsert;
     private Date auFechaupdt;
     private Integer auUserupdt;
     private String telefono;
     private String direccion;
     private Set<Rxinterface> rxinterfaces = new HashSet<Rxinterface>(0);

    public Aseguradoras() {
    }

	
    public Aseguradoras(int idaseguradora) {
        this.idaseguradora = idaseguradora;
    }
    public Aseguradoras(int idaseguradora, String aseguradora, Date auFechainsert, Integer auUserinsert, Date auFechaupdt, Integer auUserupdt, String telefono, String direccion, Set<Rxinterface> rxinterfaces) {
       this.idaseguradora = idaseguradora;
       this.aseguradora = aseguradora;
       this.auFechainsert = auFechainsert;
       this.auUserinsert = auUserinsert;
       this.auFechaupdt = auFechaupdt;
       this.auUserupdt = auUserupdt;
       this.telefono = telefono;
       this.direccion = direccion;
       this.rxinterfaces = rxinterfaces;
    }
   
    public int getIdaseguradora() {
        return this.idaseguradora;
    }
    
    public void setIdaseguradora(int idaseguradora) {
        this.idaseguradora = idaseguradora;
    }
    public String getAseguradora() {
        return this.aseguradora;
    }
    
    public void setAseguradora(String aseguradora) {
        this.aseguradora = aseguradora;
    }
    public Date getAuFechainsert() {
        return this.auFechainsert;
    }
    
    public void setAuFechainsert(Date auFechainsert) {
        this.auFechainsert = auFechainsert;
    }
    public Integer getAuUserinsert() {
        return this.auUserinsert;
    }
    
    public void setAuUserinsert(Integer auUserinsert) {
        this.auUserinsert = auUserinsert;
    }
    public Date getAuFechaupdt() {
        return this.auFechaupdt;
    }
    
    public void setAuFechaupdt(Date auFechaupdt) {
        this.auFechaupdt = auFechaupdt;
    }
    public Integer getAuUserupdt() {
        return this.auUserupdt;
    }
    
    public void setAuUserupdt(Integer auUserupdt) {
        this.auUserupdt = auUserupdt;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set<Rxinterface> getRxinterfaces() {
        return this.rxinterfaces;
    }
    
    public void setRxinterfaces(Set<Rxinterface> rxinterfaces) {
        this.rxinterfaces = rxinterfaces;
    }




}


