package model;
// Generated Dec 22, 2019 8:33:35 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Medicos generated by hbm2java
 */
public class Medicos  implements java.io.Serializable {


     private long idmedico;
     private Usuarios usuarios;
     private String nombremedico;
     private String apellidomedico;
     private String juntavigilancia;
     private String especialidad;
     private String clinica;
     private String direccionclinica;
     private String telefono;
     private String celular;
     private String email;
     private Boolean activo;
     private Date fecharegistro;
     private String tipo;
     private Date auFechainsert;
     private Integer auUserinsert;
     private Date auFechaupdt;
     private Integer auUserupdt;
     private Integer estudioagendado;
     private Integer estudiocancelado;
     private Set<Rxinterface> rxinterfaces = new HashSet<Rxinterface>(0);

    public Medicos() {
    }

	
    public Medicos(long idmedico, String nombremedico, String apellidomedico) {
        this.idmedico = idmedico;
        this.nombremedico = nombremedico;
        this.apellidomedico = apellidomedico;
    }
    public Medicos(long idmedico, Usuarios usuarios, String nombremedico, String apellidomedico, String juntavigilancia, String especialidad, String clinica, String direccionclinica, String telefono, String celular, String email, Boolean activo, Date fecharegistro, String tipo, Date auFechainsert, Integer auUserinsert, Date auFechaupdt, Integer auUserupdt, Integer estudioagendado, Integer estudiocancelado, Set<Rxinterface> rxinterfaces) {
       this.idmedico = idmedico;
       this.usuarios = usuarios;
       this.nombremedico = nombremedico;
       this.apellidomedico = apellidomedico;
       this.juntavigilancia = juntavigilancia;
       this.especialidad = especialidad;
       this.clinica = clinica;
       this.direccionclinica = direccionclinica;
       this.telefono = telefono;
       this.celular = celular;
       this.email = email;
       this.activo = activo;
       this.fecharegistro = fecharegistro;
       this.tipo = tipo;
       this.auFechainsert = auFechainsert;
       this.auUserinsert = auUserinsert;
       this.auFechaupdt = auFechaupdt;
       this.auUserupdt = auUserupdt;
       this.estudioagendado = estudioagendado;
       this.estudiocancelado = estudiocancelado;
       this.rxinterfaces = rxinterfaces;
    }
   
    public long getIdmedico() {
        return this.idmedico;
    }
    
    public void setIdmedico(long idmedico) {
        this.idmedico = idmedico;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getNombremedico() {
        return this.nombremedico;
    }
    
    public void setNombremedico(String nombremedico) {
        this.nombremedico = nombremedico;
    }
    public String getApellidomedico() {
        return this.apellidomedico;
    }
    
    public void setApellidomedico(String apellidomedico) {
        this.apellidomedico = apellidomedico;
    }
    public String getJuntavigilancia() {
        return this.juntavigilancia;
    }
    
    public void setJuntavigilancia(String juntavigilancia) {
        this.juntavigilancia = juntavigilancia;
    }
    public String getEspecialidad() {
        return this.especialidad;
    }
    
    public void setEspecialidad(String especialidad) {
        this.especialidad = especialidad;
    }
    public String getClinica() {
        return this.clinica;
    }
    
    public void setClinica(String clinica) {
        this.clinica = clinica;
    }
    public String getDireccionclinica() {
        return this.direccionclinica;
    }
    
    public void setDireccionclinica(String direccionclinica) {
        this.direccionclinica = direccionclinica;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }
    public Date getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Date getAuFechainsert() {
        return this.auFechainsert;
    }
    
    public void setAuFechainsert(Date auFechainsert) {
        this.auFechainsert = auFechainsert;
    }
    public Integer getAuUserinsert() {
        return this.auUserinsert;
    }
    
    public void setAuUserinsert(Integer auUserinsert) {
        this.auUserinsert = auUserinsert;
    }
    public Date getAuFechaupdt() {
        return this.auFechaupdt;
    }
    
    public void setAuFechaupdt(Date auFechaupdt) {
        this.auFechaupdt = auFechaupdt;
    }
    public Integer getAuUserupdt() {
        return this.auUserupdt;
    }
    
    public void setAuUserupdt(Integer auUserupdt) {
        this.auUserupdt = auUserupdt;
    }
    public Integer getEstudioagendado() {
        return this.estudioagendado;
    }
    
    public void setEstudioagendado(Integer estudioagendado) {
        this.estudioagendado = estudioagendado;
    }
    public Integer getEstudiocancelado() {
        return this.estudiocancelado;
    }
    
    public void setEstudiocancelado(Integer estudiocancelado) {
        this.estudiocancelado = estudiocancelado;
    }
    public Set<Rxinterface> getRxinterfaces() {
        return this.rxinterfaces;
    }
    
    public void setRxinterfaces(Set<Rxinterface> rxinterfaces) {
        this.rxinterfaces = rxinterfaces;
    }




}


