package model;
// Generated Dec 22, 2019 8:33:35 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Paciente generated by hbm2java
 */
public class Paciente  implements java.io.Serializable {


     private String idPaciente;
     private String namepatient;
     private String lastnamepatient;
     private String gender;
     private Date datebirth;
     private String adress;
     private String phone;
     private String extid;
     private String email;
     private Date dateadmission;
     private Boolean activo;
     private String passport;
     private Boolean adt08;
     private Boolean adt14;
     private Date auFechainsert;
     private Integer auUserinsert;
     private Date auFechaupdt;
     private Integer auUserupdt;
     private Set<Rxinterface> rxinterfaces = new HashSet<Rxinterface>(0);

    public Paciente() {
    }

	
    public Paciente(String idPaciente, String namepatient, String lastnamepatient, String gender, Date datebirth) {
        this.idPaciente = idPaciente;
        this.namepatient = namepatient;
        this.lastnamepatient = lastnamepatient;
        this.gender = gender;
        this.datebirth = datebirth;
    }
    public Paciente(String idPaciente, String namepatient, String lastnamepatient, String gender, Date datebirth, String adress, String phone, String extid, String email, Date dateadmission, Boolean activo, String passport, Boolean adt08, Boolean adt14, Date auFechainsert, Integer auUserinsert, Date auFechaupdt, Integer auUserupdt, Set<Rxinterface> rxinterfaces) {
       this.idPaciente = idPaciente;
       this.namepatient = namepatient;
       this.lastnamepatient = lastnamepatient;
       this.gender = gender;
       this.datebirth = datebirth;
       this.adress = adress;
       this.phone = phone;
       this.extid = extid;
       this.email = email;
       this.dateadmission = dateadmission;
       this.activo = activo;
       this.passport = passport;
       this.adt08 = adt08;
       this.adt14 = adt14;
       this.auFechainsert = auFechainsert;
       this.auUserinsert = auUserinsert;
       this.auFechaupdt = auFechaupdt;
       this.auUserupdt = auUserupdt;
       this.rxinterfaces = rxinterfaces;
    }
   
    public String getIdPaciente() {
        return this.idPaciente;
    }
    
    public void setIdPaciente(String idPaciente) {
        this.idPaciente = idPaciente;
    }
    public String getNamepatient() {
        return this.namepatient;
    }
    
    public void setNamepatient(String namepatient) {
        this.namepatient = namepatient;
    }
    public String getLastnamepatient() {
        return this.lastnamepatient;
    }
    
    public void setLastnamepatient(String lastnamepatient) {
        this.lastnamepatient = lastnamepatient;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public Date getDatebirth() {
        return this.datebirth;
    }
    
    public void setDatebirth(Date datebirth) {
        this.datebirth = datebirth;
    }
    public String getAdress() {
        return this.adress;
    }
    
    public void setAdress(String adress) {
        this.adress = adress;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getExtid() {
        return this.extid;
    }
    
    public void setExtid(String extid) {
        this.extid = extid;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getDateadmission() {
        return this.dateadmission;
    }
    
    public void setDateadmission(Date dateadmission) {
        this.dateadmission = dateadmission;
    }
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }
    public String getPassport() {
        return this.passport;
    }
    
    public void setPassport(String passport) {
        this.passport = passport;
    }
    public Boolean getAdt08() {
        return this.adt08;
    }
    
    public void setAdt08(Boolean adt08) {
        this.adt08 = adt08;
    }
    public Boolean getAdt14() {
        return this.adt14;
    }
    
    public void setAdt14(Boolean adt14) {
        this.adt14 = adt14;
    }
    public Date getAuFechainsert() {
        return this.auFechainsert;
    }
    
    public void setAuFechainsert(Date auFechainsert) {
        this.auFechainsert = auFechainsert;
    }
    public Integer getAuUserinsert() {
        return this.auUserinsert;
    }
    
    public void setAuUserinsert(Integer auUserinsert) {
        this.auUserinsert = auUserinsert;
    }
    public Date getAuFechaupdt() {
        return this.auFechaupdt;
    }
    
    public void setAuFechaupdt(Date auFechaupdt) {
        this.auFechaupdt = auFechaupdt;
    }
    public Integer getAuUserupdt() {
        return this.auUserupdt;
    }
    
    public void setAuUserupdt(Integer auUserupdt) {
        this.auUserupdt = auUserupdt;
    }
    public Set<Rxinterface> getRxinterfaces() {
        return this.rxinterfaces;
    }
    
    public void setRxinterfaces(Set<Rxinterface> rxinterfaces) {
        this.rxinterfaces = rxinterfaces;
    }




}


