package model;
// Generated Dec 22, 2019 8:33:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Plantillas generated by hbm2java
 */
public class Plantillas  implements java.io.Serializable {


     private int idplantilla;
     private String plantilla;
     private String nombre;
     private Date fecha;
     private Boolean activo;
     private String modalidad;
     private Long iduser;

    public Plantillas() {
    }

	
    public Plantillas(int idplantilla) {
        this.idplantilla = idplantilla;
    }
    public Plantillas(int idplantilla, String plantilla, String nombre, Date fecha, Boolean activo, String modalidad, Long iduser) {
       this.idplantilla = idplantilla;
       this.plantilla = plantilla;
       this.nombre = nombre;
       this.fecha = fecha;
       this.activo = activo;
       this.modalidad = modalidad;
       this.iduser = iduser;
    }
   
    public int getIdplantilla() {
        return this.idplantilla;
    }
    
    public void setIdplantilla(int idplantilla) {
        this.idplantilla = idplantilla;
    }
    public String getPlantilla() {
        return this.plantilla;
    }
    
    public void setPlantilla(String plantilla) {
        this.plantilla = plantilla;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }
    public String getModalidad() {
        return this.modalidad;
    }
    
    public void setModalidad(String modalidad) {
        this.modalidad = modalidad;
    }
    public Long getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Long iduser) {
        this.iduser = iduser;
    }




}


