package model;
// Generated Dec 22, 2019 8:33:35 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proyecciones generated by hbm2java
 */
public class Proyecciones  implements java.io.Serializable {


     private long cpt;
     private String proc;
     private String modality;
     private boolean activo;
     private BigDecimal precio;
     private Date fecha;
     private Date auFechainsert;
     private Integer auUserinsert;
     private Date auFechaupdt;
     private Integer auUserupdt;
     private Set<Rxinterface> rxinterfaces = new HashSet<Rxinterface>(0);

    public Proyecciones() {
    }

	
    public Proyecciones(long cpt, String proc, boolean activo, Date fecha) {
        this.cpt = cpt;
        this.proc = proc;
        this.activo = activo;
        this.fecha = fecha;
    }
    public Proyecciones(long cpt, String proc, String modality, boolean activo, BigDecimal precio, Date fecha, Date auFechainsert, Integer auUserinsert, Date auFechaupdt, Integer auUserupdt, Set<Rxinterface> rxinterfaces) {
       this.cpt = cpt;
       this.proc = proc;
       this.modality = modality;
       this.activo = activo;
       this.precio = precio;
       this.fecha = fecha;
       this.auFechainsert = auFechainsert;
       this.auUserinsert = auUserinsert;
       this.auFechaupdt = auFechaupdt;
       this.auUserupdt = auUserupdt;
       this.rxinterfaces = rxinterfaces;
    }
   
    public long getCpt() {
        return this.cpt;
    }
    
    public void setCpt(long cpt) {
        this.cpt = cpt;
    }
    public String getProc() {
        return this.proc;
    }
    
    public void setProc(String proc) {
        this.proc = proc;
    }
    public String getModality() {
        return this.modality;
    }
    
    public void setModality(String modality) {
        this.modality = modality;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getAuFechainsert() {
        return this.auFechainsert;
    }
    
    public void setAuFechainsert(Date auFechainsert) {
        this.auFechainsert = auFechainsert;
    }
    public Integer getAuUserinsert() {
        return this.auUserinsert;
    }
    
    public void setAuUserinsert(Integer auUserinsert) {
        this.auUserinsert = auUserinsert;
    }
    public Date getAuFechaupdt() {
        return this.auFechaupdt;
    }
    
    public void setAuFechaupdt(Date auFechaupdt) {
        this.auFechaupdt = auFechaupdt;
    }
    public Integer getAuUserupdt() {
        return this.auUserupdt;
    }
    
    public void setAuUserupdt(Integer auUserupdt) {
        this.auUserupdt = auUserupdt;
    }
    public Set<Rxinterface> getRxinterfaces() {
        return this.rxinterfaces;
    }
    
    public void setRxinterfaces(Set<Rxinterface> rxinterfaces) {
        this.rxinterfaces = rxinterfaces;
    }




}


