package model;
// Generated Dec 22, 2019 8:33:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Rxfusion generated by hbm2java
 */
public class Rxfusion  implements java.io.Serializable {


     private int idfusion;
     private String idmasterpatient;
     private String idmrg;
     private String accfusion;
     private Date fechaestudioant;
     private Date auFechainsert;
     private Integer auUserinsert;
     private Date auFechaupdt;
     private Integer auUserupdt;
     private Date fecha;

    public Rxfusion() {
    }

	
    public Rxfusion(int idfusion) {
        this.idfusion = idfusion;
    }
    public Rxfusion(int idfusion, String idmasterpatient, String idmrg, String accfusion, Date fechaestudioant, Date auFechainsert, Integer auUserinsert, Date auFechaupdt, Integer auUserupdt, Date fecha) {
       this.idfusion = idfusion;
       this.idmasterpatient = idmasterpatient;
       this.idmrg = idmrg;
       this.accfusion = accfusion;
       this.fechaestudioant = fechaestudioant;
       this.auFechainsert = auFechainsert;
       this.auUserinsert = auUserinsert;
       this.auFechaupdt = auFechaupdt;
       this.auUserupdt = auUserupdt;
       this.fecha = fecha;
    }
   
    public int getIdfusion() {
        return this.idfusion;
    }
    
    public void setIdfusion(int idfusion) {
        this.idfusion = idfusion;
    }
    public String getIdmasterpatient() {
        return this.idmasterpatient;
    }
    
    public void setIdmasterpatient(String idmasterpatient) {
        this.idmasterpatient = idmasterpatient;
    }
    public String getIdmrg() {
        return this.idmrg;
    }
    
    public void setIdmrg(String idmrg) {
        this.idmrg = idmrg;
    }
    public String getAccfusion() {
        return this.accfusion;
    }
    
    public void setAccfusion(String accfusion) {
        this.accfusion = accfusion;
    }
    public Date getFechaestudioant() {
        return this.fechaestudioant;
    }
    
    public void setFechaestudioant(Date fechaestudioant) {
        this.fechaestudioant = fechaestudioant;
    }
    public Date getAuFechainsert() {
        return this.auFechainsert;
    }
    
    public void setAuFechainsert(Date auFechainsert) {
        this.auFechainsert = auFechainsert;
    }
    public Integer getAuUserinsert() {
        return this.auUserinsert;
    }
    
    public void setAuUserinsert(Integer auUserinsert) {
        this.auUserinsert = auUserinsert;
    }
    public Date getAuFechaupdt() {
        return this.auFechaupdt;
    }
    
    public void setAuFechaupdt(Date auFechaupdt) {
        this.auFechaupdt = auFechaupdt;
    }
    public Integer getAuUserupdt() {
        return this.auUserupdt;
    }
    
    public void setAuUserupdt(Integer auUserupdt) {
        this.auUserupdt = auUserupdt;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


