package model;
// Generated Dec 22, 2019 8:33:35 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Rxinterface generated by hbm2java
 */
public class Rxinterface  implements java.io.Serializable {


     private long accnumber;
     private Aseguradoras aseguradoras;
     private Medicos medicos;
     private Paciente paciente;
     private Proyecciones proyecciones;
     private Usuarios usuarios;
     private String report;
     private String control;
     private String status;
     private String obsertec;
     private Date datestudy;
     private Date date;
     private Integer cantidad;
     private Date timestudy;
     private String tipopago;
     private BigDecimal pagado;
     private String institucion;
     private Double pagoaseguradora;
     private Double pagopaciente;
     private Date auFechainsert;
     private Integer auUserinsert;
     private Date auFechaupdt;
     private Integer auUserupdt;
     private Long site;
     private Long year;
     private String tipodoc;
     private String documento;

    public Rxinterface() {
        medicos = new Medicos();
        paciente = new Paciente();
        proyecciones = new Proyecciones();
        usuarios = new Usuarios();
        aseguradoras = new Aseguradoras();
    }

	
    public Rxinterface(long accnumber, Paciente paciente) {
        this.accnumber = accnumber;
        this.paciente = paciente;
    }
    public Rxinterface(long accnumber, Aseguradoras aseguradoras, Medicos medicos, Paciente paciente, Proyecciones proyecciones, Usuarios usuarios, String report, String control, String status, String obsertec, Date datestudy, Date date, Integer cantidad, Date timestudy, String tipopago, BigDecimal pagado, String institucion, Double pagoaseguradora, Double pagopaciente, Date auFechainsert, Integer auUserinsert, Date auFechaupdt, Integer auUserupdt, Long site, Long year, String tipodoc, String documento) {
       this.accnumber = accnumber;
       this.aseguradoras = aseguradoras;
       this.medicos = medicos;
       this.paciente = paciente;
       this.proyecciones = proyecciones;
       this.usuarios = usuarios;
       this.report = report;
       this.control = control;
       this.status = status;
       this.obsertec = obsertec;
       this.datestudy = datestudy;
       this.date = date;
       this.cantidad = cantidad;
       this.timestudy = timestudy;
       this.tipopago = tipopago;
       this.pagado = pagado;
       this.institucion = institucion;
       this.pagoaseguradora = pagoaseguradora;
       this.pagopaciente = pagopaciente;
       this.auFechainsert = auFechainsert;
       this.auUserinsert = auUserinsert;
       this.auFechaupdt = auFechaupdt;
       this.auUserupdt = auUserupdt;
       this.site = site;
       this.year = year;
       this.tipodoc = tipodoc;
       this.documento = documento;
    }
   
    public long getAccnumber() {
        return this.accnumber;
    }
    
    public void setAccnumber(long accnumber) {
        this.accnumber = accnumber;
    }
    public Aseguradoras getAseguradoras() {
        return this.aseguradoras;
    }
    
    public void setAseguradoras(Aseguradoras aseguradoras) {
        this.aseguradoras = aseguradoras;
    }
    public Medicos getMedicos() {
        return this.medicos;
    }
    
    public void setMedicos(Medicos medicos) {
        this.medicos = medicos;
    }
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    public Proyecciones getProyecciones() {
        return this.proyecciones;
    }
    
    public void setProyecciones(Proyecciones proyecciones) {
        this.proyecciones = proyecciones;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getReport() {
        return this.report;
    }
    
    public void setReport(String report) {
        this.report = report;
    }
    public String getControl() {
        return this.control;
    }
    
    public void setControl(String control) {
        this.control = control;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getObsertec() {
        return this.obsertec;
    }
    
    public void setObsertec(String obsertec) {
        this.obsertec = obsertec;
    }
    public Date getDatestudy() {
        return this.datestudy;
    }
    
    public void setDatestudy(Date datestudy) {
        this.datestudy = datestudy;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Date getTimestudy() {
        return this.timestudy;
    }
    
    public void setTimestudy(Date timestudy) {
        this.timestudy = timestudy;
    }
    public String getTipopago() {
        return this.tipopago;
    }
    
    public void setTipopago(String tipopago) {
        this.tipopago = tipopago;
    }
    public BigDecimal getPagado() {
        return this.pagado;
    }
    
    public void setPagado(BigDecimal pagado) {
        this.pagado = pagado;
    }
    public String getInstitucion() {
        return this.institucion;
    }
    
    public void setInstitucion(String institucion) {
        this.institucion = institucion;
    }
    public Double getPagoaseguradora() {
        return this.pagoaseguradora;
    }
    
    public void setPagoaseguradora(Double pagoaseguradora) {
        this.pagoaseguradora = pagoaseguradora;
    }
    public Double getPagopaciente() {
        return this.pagopaciente;
    }
    
    public void setPagopaciente(Double pagopaciente) {
        this.pagopaciente = pagopaciente;
    }
    public Date getAuFechainsert() {
        return this.auFechainsert;
    }
    
    public void setAuFechainsert(Date auFechainsert) {
        this.auFechainsert = auFechainsert;
    }
    public Integer getAuUserinsert() {
        return this.auUserinsert;
    }
    
    public void setAuUserinsert(Integer auUserinsert) {
        this.auUserinsert = auUserinsert;
    }
    public Date getAuFechaupdt() {
        return this.auFechaupdt;
    }
    
    public void setAuFechaupdt(Date auFechaupdt) {
        this.auFechaupdt = auFechaupdt;
    }
    public Integer getAuUserupdt() {
        return this.auUserupdt;
    }
    
    public void setAuUserupdt(Integer auUserupdt) {
        this.auUserupdt = auUserupdt;
    }
    public Long getSite() {
        return this.site;
    }
    
    public void setSite(Long site) {
        this.site = site;
    }
    public Long getYear() {
        return this.year;
    }
    
    public void setYear(Long year) {
        this.year = year;
    }
    public String getTipodoc() {
        return this.tipodoc;
    }
    
    public void setTipodoc(String tipodoc) {
        this.tipodoc = tipodoc;
    }
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }




}


