package model;
// Generated Dec 22, 2019 8:33:35 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private long iduser;
     private String rol;
     private String nameuser;
     private String lastnameuser;
     private String phone;
     private String emailuser;
     private Boolean activo;
     private Date inputdate;
     private String password;
     private String firstnameuser;
     private Boolean radiologo;
     private Date auFechainsert;
     private Integer auUserinsert;
     private Date auFechaupdt;
     private Integer auUserupdt;
     private Set<Medicos> medicoses = new HashSet<Medicos>(0);
     private Set<Rxinterface> rxinterfaces = new HashSet<Rxinterface>(0);

    public Usuarios() {
    }

	
    public Usuarios(long iduser, String rol, String nameuser, String lastnameuser) {
        this.iduser = iduser;
        this.rol = rol;
        this.nameuser = nameuser;
        this.lastnameuser = lastnameuser;
    }
    public Usuarios(long iduser, String rol, String nameuser, String lastnameuser, String phone, String emailuser, Boolean activo, Date inputdate, String password, String firstnameuser, Boolean radiologo, Date auFechainsert, Integer auUserinsert, Date auFechaupdt, Integer auUserupdt, Set<Medicos> medicoses, Set<Rxinterface> rxinterfaces) {
       this.iduser = iduser;
       this.rol = rol;
       this.nameuser = nameuser;
       this.lastnameuser = lastnameuser;
       this.phone = phone;
       this.emailuser = emailuser;
       this.activo = activo;
       this.inputdate = inputdate;
       this.password = password;
       this.firstnameuser = firstnameuser;
       this.radiologo = radiologo;
       this.auFechainsert = auFechainsert;
       this.auUserinsert = auUserinsert;
       this.auFechaupdt = auFechaupdt;
       this.auUserupdt = auUserupdt;
       this.medicoses = medicoses;
       this.rxinterfaces = rxinterfaces;
    }
   
    public long getIduser() {
        return this.iduser;
    }
    
    public void setIduser(long iduser) {
        this.iduser = iduser;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public String getNameuser() {
        return this.nameuser;
    }
    
    public void setNameuser(String nameuser) {
        this.nameuser = nameuser;
    }
    public String getLastnameuser() {
        return this.lastnameuser;
    }
    
    public void setLastnameuser(String lastnameuser) {
        this.lastnameuser = lastnameuser;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmailuser() {
        return this.emailuser;
    }
    
    public void setEmailuser(String emailuser) {
        this.emailuser = emailuser;
    }
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }
    public Date getInputdate() {
        return this.inputdate;
    }
    
    public void setInputdate(Date inputdate) {
        this.inputdate = inputdate;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFirstnameuser() {
        return this.firstnameuser;
    }
    
    public void setFirstnameuser(String firstnameuser) {
        this.firstnameuser = firstnameuser;
    }
    public Boolean getRadiologo() {
        return this.radiologo;
    }
    
    public void setRadiologo(Boolean radiologo) {
        this.radiologo = radiologo;
    }
    public Date getAuFechainsert() {
        return this.auFechainsert;
    }
    
    public void setAuFechainsert(Date auFechainsert) {
        this.auFechainsert = auFechainsert;
    }
    public Integer getAuUserinsert() {
        return this.auUserinsert;
    }
    
    public void setAuUserinsert(Integer auUserinsert) {
        this.auUserinsert = auUserinsert;
    }
    public Date getAuFechaupdt() {
        return this.auFechaupdt;
    }
    
    public void setAuFechaupdt(Date auFechaupdt) {
        this.auFechaupdt = auFechaupdt;
    }
    public Integer getAuUserupdt() {
        return this.auUserupdt;
    }
    
    public void setAuUserupdt(Integer auUserupdt) {
        this.auUserupdt = auUserupdt;
    }
    public Set<Medicos> getMedicoses() {
        return this.medicoses;
    }
    
    public void setMedicoses(Set<Medicos> medicoses) {
        this.medicoses = medicoses;
    }
    public Set<Rxinterface> getRxinterfaces() {
        return this.rxinterfaces;
    }
    
    public void setRxinterfaces(Set<Rxinterface> rxinterfaces) {
        this.rxinterfaces = rxinterfaces;
    }




}


